### ISSUE TITLE
[Bug] MPO torchrun训练爆显存

### ISSUE THREAD

**Issue by Harley-Sun** [OpenGVLab/InternVL#786]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

基于官方默认的参数修改写为torchrun启动，PER_DEVICE_BATCH_SIZE改成1在80G A800上运行依然会爆显存，减小max_seq_length也不能解决问题。

### Reproduction

set -x

PARTITION=${PARTITION:-"Intern5"}
GPUS=${GPUS:-256}
GPUS_PER_NODE=${GPUS_PER_NODE:-8}
QUOTA_TYPE=${QUOTA_TYPE:-"reserved"}
NODES=$((GPUS / GPUS_PER_NODE))
CPUS_PER_TASK=${CPUS_PER_TASK:-10}
SRUN_ARGS=${SRUN_ARGS:-""}
BATCH_SIZE=${BATCH_SIZE:-256}
PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-1}
GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))

export PYTHONPATH="/mnt/petrelfs/wangweiyun/workspace_cz/InternVL/internvl_chat_dev/petrel-oss-python-sdk"
export PYTHONPATH="${PYTHONPATH}:$(pwd)"
export MASTER_PORT=34729
export TF_CPP_MIN_LOG_LEVEL=3
export LAUNCHER=pytorch
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

OUTPUT_DIR='work_dirs/mpo'

if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
fi

torchrun \
  --nnodes=1 \
  --node_rank=0 \
  --master_addr=127.0.0.1 \
  --nproc_per_node=${GPUS} \
  --master_port=${MASTER_PORT} \
  internvl/train/internvl_chat_dpo.py \
  --model_name_or_path "work_dirs/InternVL2-8B" \
  --conv_style "internlm2-chat" \
  --output_dir ${OUTPUT_DIR} \
  --meta_path "MMPR/meta.json" \
  --overwrite_output_dir True \
  --force_image_size 448 \
  --down_sample_ratio 0.5 \
  --drop_path_rate 0.1 \
  --pad2square False \
  --freeze_llm False \
  --freeze_mlp False \
  --freeze_backbone False \
  --vision_select_layer -1 \
  --use_data_resampling False \
  --dataloader_num_workers 8 \
  --bf16 True \
  --num_train_epochs 1 \
  --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
  --gradient_accumulation_steps ${GRADIENT_ACC} \
  --evaluation_strategy "no" \
  --save_strategy "no" \
  --save_steps 100 \
  --save_total_limit 100 \
  --learning_rate 5e-6 \
  --weight_decay 0.05 \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --max_seq_length 2048 \
  --do_train True \
  --grad_checkpoint True \
  --group_by_length False \
  --dynamic_image_size True \
  --use_thumbnail True \
  --ps_version 'v2' \
  --deepspeed "zero_stage1_config.json" \
  --report_to "tensorboard" \
  --loss_type sigmoid,bco_pair \
  --sigmoid_loss_weight 0.8 \
  --bco_pair_loss_weight 0.2 \
  --rpo_alpha 1 \
  2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"

### Environment

```Shell
sys.platform: linux
Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-80GB
CUDA_HOME: /ssd1/home/envs/cuda-11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 10.1.0
PyTorch: 2.2.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=
sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIB
KINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-a
rray-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color
=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.0, USE_CUDA=ON, USE_CUDNN=ON, USE_E
XCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.0+cu118
LMDeploy: 0.4.2+
transformers: 4.37.2
gradio: 4.38.1
fastapi: 0.111.0
pydantic: 2.9.2
triton: 2.2.0
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/ssd1/home/code/InternVL-main/internvl_chat/internvl/train/internvl_chat_dpo.py", line 961, in <module>
    main()
  File "/ssd1/home/code/InternVL-main/internvl_chat/internvl/train/internvl_chat_dpo.py", line 946, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/accelerate/accelerator.py", line 2116, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 175, in backward
    self.engine.step()
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2169, in step
    self._take_model_step(lr_kwargs)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
    self.optimizer.step()
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1898, in step
    self._optimizer_step(i)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1805, in _optimizer_step
    self.optimizer.step()
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/torch/optim/optimizer.py", line 385, in wrapper
    out = func(*args, **kwargs)
  File "/ssd1/home/anaconda3/envs/mllm/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 157, in step
    state['exp_avg_sq'] = torch.zeros_like(p.data)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 15.04 GiB. GPU 1 has a total capacity of 79.33 GiB of which 1.03 GiB is free. Including non-PyTorch memory, this process has 78.29 GiB memory in use. Of the allocated memory 76.25 GiB is allocated by PyTorch,
 and 679.95 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html
#environment-variables)
```

**Comment by Weiyun1025** [comment]
建议参考我们[新发布的脚本](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/internvl2.5_mpo/preference_optimization/internvl2_5_8b_internlm2_5_7b_dynamic_res_mpo.sh#L76)把`use_liger`设置为`True`，这个对减少显存占用的收益很明显

**Comment by Harley-Sun** [comment]
> 建议参考我们[新发布的脚本](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/internvl2.5_mpo/preference_optimization/internvl2_5_8b_internlm2_5_7b_dynamic_res_mpo.sh#L76)把`use_liger`设置为`True`，这个对减少显存占用的收益很明显

你好能给一个可以参考的环境配置吗？特别是liger_kernel的版本，我装完liger后各种环境问题。。

**Comment by Weiyun1025** [comment]
我传了一个[conda环境](https://huggingface.co/datasets/Weiyun1025/internvl-mpo-torch2.5.1)到HF上，你可以参考一下，`conda list`结果如下：

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   2.1.0                    pypi_0    pypi
accelerate                1.1.1                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiohappyeyeballs          2.4.4                    pypi_0    pypi
aiohttp                   3.11.9                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
boto3                     1.35.73                  pypi_0    pypi
botocore                  1.35.73                  pypi_0    pypi
brotli-python             1.1.0           py311hfdbb021_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py311hf29c0ef_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.3.1                    pypi_0    pypi
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.6.77                       0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cuda-version              12.6                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
datasets                  3.1.0                    pypi_0    pypi
decord                    0.6.0                    pypi_0    pypi
deepspeed                 0.15.4                   pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docstring-parser          0.16                     pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
environs                  11.0.0                   pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
flash-attn                2.7.0.post2              pypi_0    pypi
fonttools                 4.55.0                   pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
frozenlist                1.5.0                    pypi_0    pypi
fsspec                    2024.9.0                 pypi_0    pypi
giflib                    5.2.2                hd590300_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5           py311h0f6cedb_2    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
grpcio                    1.68.1                   pypi_0    pypi
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hjson                     3.1.0                    pypi_0    pypi
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
huggingface-hub           0.26.3                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
humanize                  4.11.0                   pypi_0    pypi
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
imageio                   2.36.1                   pypi_0    pypi
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
kiwisolver                1.4.7                    pypi_0    pypi
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.11.1.6                      0    nvidia
libcurand                 10.3.7.77                     0    nvidia
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libdeflate                1.17                 h0b41bf4_0    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libhwloc                  2.11.2          default_he43201b_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libnpp                    12.0.2.50                     0    nvidia
libnsl                    2.0.1                hd590300_0    conda-forge
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.2.4                h1daa5a0_1    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
liger-kernel              0.4.2                    pypi_0    pypi
llvm-openmp               15.0.7               h0cdce71_0    conda-forge
lmdeploy                  0.6.4                    pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2           py311h2dc5d0c_0    conda-forge
marshmallow               3.23.1                   pypi_0    pypi
matplotlib                3.9.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
mmengine                  0.10.5                   pypi_0    pypi
mpc                       1.3.1                h24ddda3_1    conda-forge
mpfr                      4.2.1                h90cbb55_3    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msgpack                   1.1.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
multiprocessing-logging   0.3.4                    pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
networkx                  3.4.2              pyh267e887_2    conda-forge
ninja                     1.11.1.2                 pypi_0    pypi
numpy                     2.1.3           py311h71ddf71_0    conda-forge
opencv-python             4.10.0.84                pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
packaging                 24.2                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
peft                      0.13.2                   pypi_0    pypi
pillow                    9.4.0           py311h50def17_1    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
platformdirs              4.3.6                    pypi_0    pypi
propcache                 0.2.1                    pypi_0    pypi
protobuf                  5.29.0                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   18.1.0                   pypi_0    pypi
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.10.2                   pypi_0    pypi
pydantic-core             2.27.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python_abi                3.11                    5_cp311    conda-forge
pytorch                   2.5.1           py3.11_cuda12.1_cudnn9.1.0_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_6    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2           py311h9ecbd09_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
regex                     2024.11.6                pypi_0    pypi
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.9.4                   pypi_0    pypi
s3transfer                0.10.4                   pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                75.6.0             pyhff2d567_1    conda-forge
shtab                     1.7.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tbb                       2021.13.0            hceb3a55_1    conda-forge
tensorboard               2.18.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
termcolor                 2.5.0                    pypi_0    pypi
timm                      1.0.11                   pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tokenizers                0.20.3                   pypi_0    pypi
torchaudio                2.5.1               py311_cu121    pytorch
torchtriton               3.1.0                     py311    pytorch
torchvision               0.20.1              py311_cu121    pytorch
tqdm                      4.67.1                   pypi_0    pypi
transformers              4.45.1                   pypi_0    pypi
trl                       0.10.1                   pypi_0    pypi
typeguard                 4.4.1                    pypi_0    pypi
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tyro                      0.9.2                    pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
werkzeug                  3.1.3                    pypi_0    pypi
wheel                     0.45.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yapf                      0.43.0                   pypi_0    pypi
yarl                      1.18.3                   pypi_0    pypi
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.23.0          py311hbc35293_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by Harley-Sun** [comment]
> 建议参考我们[新发布的脚本](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/internvl2.5_mpo/preference_optimization/internvl2_5_8b_internlm2_5_7b_dynamic_res_mpo.sh#L76)把`use_liger`设置为`True`，这个对减少显存占用的收益很明显

liger打开了显存还是会爆，请问你们在训练的时候单卡显存会占用多少呢？有没有什么好的解决办法？

**Comment by Weiyun1025** [comment]
```shell
torchrun
--nnodes=1
--node_rank=0
--master_addr=127.0.0.1
--nproc_per_node=${GPUS}
--master_port=${MASTER_PORT}
internvl/train/internvl_chat_dpo.py
```
你这里`${GPUS}`设置的是256，但是nnodes只有1，假设你的节点有八张卡，相当于每张卡要跑32个任务，这个是肯定要爆显存的，可以参考[torchrun](https://pytorch.org/docs/stable/elastic/run.html)的文档根据你的节点和显卡数量修改一下参数

**Comment by zhangzef** [comment]
爆显存的问题解决了吗，我遇到了同样的问题，尽管我使用了zero3+offload也无法训练internvl2_5_8b，但是当我讲max_seq_len设置为1024时可以正常训练，下面是我的训练指令：
```bash
set -x

GPUS=${GPUS:-8}
BATCH_SIZE=${BATCH_SIZE:-256}
PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-1}
GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))

# export PYTHONPATH="${PYTHONPATH}:$(pwd)"
export TRITON_CACHE_DIR="./trition/"
export MASTER_PORT=34229
export TF_CPP_MIN_LOG_LEVEL=3

OUTPUT_DIR='work_dirs/internvl_chat_v2_5_mpo/Internvl2_5-8B-MPO'

if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
fi

deepspeed \
  internvl/train/internvl_chat_dpo_new.py \
  --model_name_or_path "./models/InternVL2_5-8B" \
  --conv_style "internvl2_5" \
  --output_dir ${OUTPUT_DIR} \
  --meta_path "./data/MMPR-v1.1/meta.json" \
  --overwrite_output_dir True \
  --force_image_size 448 \
  --down_sample_ratio 0.5 \
  --drop_path_rate 0.1 \
  --pad2square False \
  --freeze_llm False \
  --freeze_mlp False \
  --freeze_backbone False \
  --vision_select_layer -1 \
  --use_data_resampling False \
  --dataloader_num_workers 8 \
  --bf16 True \
  --num_train_epochs 1 \
  --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
  --gradient_accumulation_steps ${GRADIENT_ACC} \
  --evaluation_strategy "no" \
  --save_strategy "epoch" \
  --save_steps 100 \
  --save_total_limit 2 \
  --learning_rate 1e-6 \
  --weight_decay 0.05 \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --max_seq_length 8192 \
  --do_train True \
  --grad_checkpoint True \
  --group_by_length False \
  --dynamic_image_size True \
  --use_thumbnail True \
  --ps_version 'v2' \
  --deepspeed "zero_stage3_offload_config.json" \
  --report_to "tensorboard" \
  --loss_type sigmoid,bco_pair \
  --sigmoid_loss_weight 0.8 \
  --bco_pair_loss_weight 0.2 \
  --rpo_alpha 1 \
  --use_liger True \
  2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"
```

以及我的zero3-offload配置文件：
```json
{
  "zero_optimization": {
    "stage": 3,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
    "offload_param": {
      "device": "cpu",
      "pin_memory": true
    },
    "allgather_partitions": true,
    "allgather_bucket_size": 1e5,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1e5,
    "contiguous_gradients": true,
    "sub_group_size": 1e5
  },
  "fp16": {
    "enabled": "auto",
    "auto_cast": true,
    "loss_scale": 0,
    "initial_scale_power": 32,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-8,
      "weight_decay": "auto"
    }
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": true
}
```

此时程序在运行时会突然退出并显示`exits with return code = -11`，GPT告诉我是段溢出问题（可能是显存或者内存oom）

**Comment by zhangzef** [comment]
然而当我的所有设置不变，将deepspeed配置换为zero2+offload，配置文件如下：
```json
{
  "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 1e5,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1e5,
    "contiguous_gradients": true,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    }
  },
  "fp16": {
    "enabled": "auto",
    "auto_cast": true,
    "loss_scale": 0,
    "initial_scale_power": 32,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": [
        0.9,
        0.999
      ],
      "eps": 1e-8,
      "weight_decay": "auto"
    }
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

此时程序会报如下错误：
```bash
[rank5]: Traceback (most recent call last):
[rank5]:   File "/root/paddlejob/workspace/output/zzf/codes/InternVL/internvl_chat/internvl/train/internvl_chat_dpo_new.py", line 1056, in <module>
[rank5]:     main()
[rank5]:   File "/root/paddlejob/workspace/output/zzf/codes/InternVL/internvl_chat/internvl/train/internvl_chat_dpo_new.py", line 1027, in main
[rank5]:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
[rank5]:   File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/trainer.py", line 2052, in train
[rank5]:     return inner_training_loop(
[rank5]:   File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/trainer.py", line 2388, in _inner_training_loop
[rank5]:     tr_loss_step = self.training_step(model, inputs)
[rank5]:   File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/trainer.py", line 3485, in training_step
[rank5]:     loss = self.compute_loss(model, inputs)
[rank5]:   File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/trl/trainer/dpo_trainer.py", line 1520, in compute_loss
[rank5]:     loss, metrics = self.get_batch_loss_metrics(model, inputs, train_eval="train")
[rank5]:   File "/root/paddlejob/workspace/output/zzf/codes/InternVL/internvl_chat/internvl/train/trainer_dpo.py", line 252, in get_batch_loss_metrics
[rank5]:     ) = self.concatenated_forward(self.ref_model, batch)
[rank5]:   File "/root/paddlejob/workspace/output/zzf/codes/InternVL/internvl_chat/internvl/train/trainer_dpo.py", line 139, in concatenated_forward
[rank5]:     all_logps, size_completion = self.get_batch_logps(
[rank5]:   File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/trl/trainer/dpo_trainer.py", line 1342, in get_batch_logps
[rank5]:     per_token_logps = torch.gather(logits.log_softmax(-1), dim=2, index=labels.unsqueeze(2)).squeeze(2)
[rank5]: RuntimeError: r.nvmlDeviceGetNvLinkRemoteDeviceType_ INTERNAL ASSERT FAILED at "../c10/cuda/driver_api.cpp":27, please report a bug to PyTorch. Can't find nvmlDeviceGetNvLinkRemoteDeviceType: /home/opt/gpuproxy/lib64/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetNvLinkRemoteDeviceType
```
我尝试了许多办法都无法确定问题的来源（我认为最大的可能是oom）

**Comment by zhangzef** [comment]
我的环境为单机八卡80gh100，按理说如果作者可以使用默认设置`zero1`、`max_seq_len=8192`和`batch_size=1`训练起来我在80g的gpu上使用zero1应该同样能训练起来（或者作者使用的更大显存的gpu

当我使用`max_seq_len=1024`时模型确实可以正常训练了，但是会抛出大量异常：
```bash
 The size of tensor a (1964) must match the size of tensor b (2560) at non-singleton dimension 0, input_embeds[selected].shape=torch.Size([1964, 4096]), vit_embeds.shape=torch.Size([2560, 4096])
warning: The size of tensor a (1964) must match the size of tensor b (3584) at non-singleton dimension 0, input_embeds[selected].shape=torch.Size([1964, 4096]), vit_embeds.shape=torch.Size([3584, 4096])
warning: The size of tensor a (1964) must match the size of tensor b (6656) at non-singleton dimension 0, input_embeds[selected].shape=torch.Size([1964, 4096]), vit_embeds.shape=torch.Size([6656, 4096])
warning: The size of tensor a (1964) must match the size of tensor b (3584) at non-singleton dimension 0, input_embeds[selected].shape=torch.Size([1964, 4096]), vit_embeds.shape=torch.Size([3584, 4096])
```

**Comment by zhangzef** [comment]
by the way
我在使用mmpr数据集训练internvl2-8b时会出现缺少图像，RLAIF-V数据集中缺少一张Emma_Robert的图像是为什么，我后来下载了MMPRv1.1之后发现还是没有这张图像，但是似乎使用repeat_time给过滤掉了？（我还没训练到这么长的step）

**Comment by Weiyun1025** [comment]
> 爆显存的问题解决了吗，我遇到了同样的问题，尽管我使用了zero3+offload也无法训练internvl2_5_8b，但是当我讲max_seq_len设置为1024时可以正常训练，下面是我的训练指令：
> 
> ```shell
> set -x
> 
> GPUS=${GPUS:-8}
> BATCH_SIZE=${BATCH_SIZE:-256}
> PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-1}
> GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))
> 
> # export PYTHONPATH="${PYTHONPATH}:$(pwd)"
> export TRITON_CACHE_DIR="./trition/"
> export MASTER_PORT=34229
> export TF_CPP_MIN_LOG_LEVEL=3
> 
> OUTPUT_DIR='work_dirs/internvl_chat_v2_5_mpo/Internvl2_5-8B-MPO'
> 
> if [ ! -d "$OUTPUT_DIR" ]; then
>   mkdir -p "$OUTPUT_DIR"
> fi
> 
> deepspeed \
>   internvl/train/internvl_chat_dpo_new.py \
>   --model_name_or_path "./models/InternVL2_5-8B" \
>   --conv_style "internvl2_5" \
>   --output_dir ${OUTPUT_DIR} \
>   --meta_path "./data/MMPR-v1.1/meta.json" \
>   --overwrite_output_dir True \
>   --force_image_size 448 \
>   --down_sample_ratio 0.5 \
>   --drop_path_rate 0.1 \
>   --pad2square False \
>   --freeze_llm False \
>   --freeze_mlp False \
>   --freeze_backbone False \
>   --vision_select_layer -1 \
>   --use_data_resampling False \
>   --dataloader_num_workers 8 \
>   --bf16 True \
>   --num_train_epochs 1 \
>   --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
>   --gradient_accumulation_steps ${GRADIENT_ACC} \
>   --evaluation_strategy "no" \
>   --save_strategy "epoch" \
>   --save_steps 100 \
>   --save_total_limit 2 \
>   --learning_rate 1e-6 \
>   --weight_decay 0.05 \
>   --warmup_ratio 0.03 \
>   --lr_scheduler_type "cosine" \
>   --logging_steps 1 \
>   --max_seq_length 8192 \
>   --do_train True \
>   --grad_checkpoint True \
>   --group_by_length False \
>   --dynamic_image_size True \
>   --use_thumbnail True \
>   --ps_version 'v2' \
>   --deepspeed "zero_stage3_offload_config.json" \
>   --report_to "tensorboard" \
>   --loss_type sigmoid,bco_pair \
>   --sigmoid_loss_weight 0.8 \
>   --bco_pair_loss_weight 0.2 \
>   --rpo_alpha 1 \
>   --use_liger True \
>   2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"
> ```
> 
> 以及我的zero3-offload配置文件：
> 
> ```json
> {
>   "zero_optimization": {
>     "stage": 3,
>     "offload_optimizer": {
>       "device": "cpu",
>       "pin_memory": true
>     },
>     "offload_param": {
>       "device": "cpu",
>       "pin_memory": true
>     },
>     "allgather_partitions": true,
>     "allgather_bucket_size": 1e5,
>     "overlap_comm": true,
>     "reduce_scatter": true,
>     "reduce_bucket_size": 1e5,
>     "contiguous_gradients": true,
>     "sub_group_size": 1e5
>   },
>   "fp16": {
>     "enabled": "auto",
>     "auto_cast": true,
>     "loss_scale": 0,
>     "initial_scale_power": 32,
>     "loss_scale_window": 1000,
>     "hysteresis": 2,
>     "min_loss_scale": 1
>   },
>   "bf16": {
>     "enabled": "auto"
>   },
>   "optimizer": {
>     "type": "AdamW",
>     "params": {
>       "lr": "auto",
>       "betas": [
>         0.9,
>         0.999
>       ],
>       "eps": 1e-8,
>       "weight_decay": "auto"
>     }
>   },
>   "gradient_accumulation_steps": "auto",
>   "gradient_clipping": "auto",
>   "steps_per_print": 2000,
>   "train_batch_size": "auto",
>   "train_micro_batch_size_per_gpu": "auto",
>   "wall_clock_breakdown": true
> }
> ```
> 
> 此时程序在运行时会突然退出并显示`exits with return code = -11`，GPT告诉我是段溢出问题（可能是显存或者内存oom）

MPO训练的时候需要加载一个reference model，所以对显存压力会比较大，我们训练的时候是用256卡训练+zero1+liger训练1～26B模型的，8卡的显存感觉还是比较困难训起来，我们近期会尝试把codebase迁移到其他更高效的库比如openrlhf来解决这个问题

**Comment by Weiyun1025** [comment]
> by the way 我在使用mmpr数据集训练internvl2-8b时会出现缺少图像，RLAIF-V数据集中缺少一张Emma_Robert的图像是为什么，我后来下载了MMPRv1.1之后发现还是没有这张图像，但是似乎使用repeat_time给过滤掉了？（我还没训练到这么长的step）

这个是正常的，RLAIF-V数据开源的时候就有图像缺失的问题，我们代码里加了对应的异常处理

**Comment by zhangzef** [comment]
> > 爆显存的问题解决了吗，我遇到了同样的问题，尽管我使用了zero3+offload也无法训练internvl2_5_8b，但是当我讲max_seq_len设置为1024时可以正常训练，下面是我的训练指令：
> > ```shell
> > set -x
> > 
> > GPUS=${GPUS:-8}
> > BATCH_SIZE=${BATCH_SIZE:-256}
> > PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-1}
> > GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))
> > 
> > # export PYTHONPATH="${PYTHONPATH}:$(pwd)"
> > export TRITON_CACHE_DIR="./trition/"
> > export MASTER_PORT=34229
> > export TF_CPP_MIN_LOG_LEVEL=3
> > 
> > OUTPUT_DIR='work_dirs/internvl_chat_v2_5_mpo/Internvl2_5-8B-MPO'
> > 
> > if [ ! -d "$OUTPUT_DIR" ]; then
> >   mkdir -p "$OUTPUT_DIR"
> > fi
> > 
> > deepspeed \
> >   internvl/train/internvl_chat_dpo_new.py \
> >   --model_name_or_path "./models/InternVL2_5-8B" \
> >   --conv_style "internvl2_5" \
> >   --output_dir ${OUTPUT_DIR} \
> >   --meta_path "./data/MMPR-v1.1/meta.json" \
> >   --overwrite_output_dir True \
> >   --force_image_size 448 \
> >   --down_sample_ratio 0.5 \
> >   --drop_path_rate 0.1 \
> >   --pad2square False \
> >   --freeze_llm False \
> >   --freeze_mlp False \
> >   --freeze_backbone False \
> >   --vision_select_layer -1 \
> >   --use_data_resampling False \
> >   --dataloader_num_workers 8 \
> >   --bf16 True \
> >   --num_train_epochs 1 \
> >   --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
> >   --gradient_accumulation_steps ${GRADIENT_ACC} \
> >   --evaluation_strategy "no" \
> >   --save_strategy "epoch" \
> >   --save_steps 100 \
> >   --save_total_limit 2 \
> >   --learning_rate 1e-6 \
> >   --weight_decay 0.05 \
> >   --warmup_ratio 0.03 \
> >   --lr_scheduler_type "cosine" \
> >   --logging_steps 1 \
> >   --max_seq_length 8192 \
> >   --do_train True \
> >   --grad_checkpoint True \
> >   --group_by_length False \
> >   --dynamic_image_size True \
> >   --use_thumbnail True \
> >   --ps_version 'v2' \
> >   --deepspeed "zero_stage3_offload_config.json" \
> >   --report_to "tensorboard" \
> >   --loss_type sigmoid,bco_pair \
> >   --sigmoid_loss_weight 0.8 \
> >   --bco_pair_loss_weight 0.2 \
> >   --rpo_alpha 1 \
> >   --use_liger True \
> >   2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 以及我的zero3-offload配置文件：
> > ```json
> > {
> >   "zero_optimization": {
> >     "stage": 3,
> >     "offload_optimizer": {
> >       "device": "cpu",
> >       "pin_memory": true
> >     },
> >     "offload_param": {
> >       "device": "cpu",
> >       "pin_memory": true
> >     },
> >     "allgather_partitions": true,
> >     "allgather_bucket_size": 1e5,
> >     "overlap_comm": true,
> >     "reduce_scatter": true,
> >     "reduce_bucket_size": 1e5,
> >     "contiguous_gradients": true,
> >     "sub_group_size": 1e5
> >   },
> >   "fp16": {
> >     "enabled": "auto",
> >     "auto_cast": true,
> >     "loss_scale": 0,
> >     "initial_scale_power": 32,
> >     "loss_scale_window": 1000,
> >     "hysteresis": 2,
> >     "min_loss_scale": 1
> >   },
> >   "bf16": {
> >     "enabled": "auto"
> >   },
> >   "optimizer": {
> >     "type": "AdamW",
> >     "params": {
> >       "lr": "auto",
> >       "betas": [
> >         0.9,
> >         0.999
> >       ],
> >       "eps": 1e-8,
> >       "weight_decay": "auto"
> >     }
> >   },
> >   "gradient_accumulation_steps": "auto",
> >   "gradient_clipping": "auto",
> >   "steps_per_print": 2000,
> >   "train_batch_size": "auto",
> >   "train_micro_batch_size_per_gpu": "auto",
> >   "wall_clock_breakdown": true
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 此时程序在运行时会突然退出并显示`exits with return code = -11`，GPT告诉我是段溢出问题（可能是显存或者内存oom）
> 
> MPO训练的时候需要加载一个reference model，所以对显存压力会比较大，我们训练的时候是用256卡训练+zero1+liger训练1～26B模型的，8卡的显存感觉还是比较困难训起来，我们近期会尝试把codebase迁移到其他更高效的库比如openrlhf来解决这个问题

感谢回复！！！我现在尝试一下通过预处理将参考模型从训练中剔除可不可以减少训练的显存压力

**Comment by 14H034160212** [comment]
@Weiyun1025 这里脚本使用的use_liger=True对应下面的代码里并没有实现internvl2这种model_type的liger_kernel加速代码。所以使用use_liger=True并不会对模型的训练加速有帮助。
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/internvl2.5_mpo/preference_optimization/internvl2_5_8b_internlm2_5_7b_dynamic_res_mpo.sh#L76

https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_dpo.py

![image](https://github.com/user-attachments/assets/c8aae449-725a-4c31-a528-4cc25aaeb5ba)


> 建议参考我们[新发布的脚本](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/internvl2.5_mpo/preference_optimization/internvl2_5_8b_internlm2_5_7b_dynamic_res_mpo.sh#L76)把`use_liger`设置为`True`，这个对减少显存占用的收益很明显

**Comment by XiaokunFeng** [comment]
我也遇到了同样的爆显存问题。
蹲一个后续。

**Comment by zhangzef** [comment]
> 我也遇到了同样的爆显存问题。 蹲一个后续。

确实8b的模型在八卡跑起来比较困难，我尝试了最终2b的模型可以成功在八卡上复现
